language: go
before_install:
  - sudo apt-get -y install scons
  - pushd /home/travis
  - git clone https://github.com/armon/bloomd 
  - cd bloomd
  - scons
  - echo -e "[bloomd]\ndata_dir=/home/vagrant\nflush_interval=60000\nport=8673\nworkers=1\nlog_level=debug" > bloomd.conf
  - pwd
  - ls -la
  - /home/travis/bloomd/bloomd -f /home/travis/bloomd/bloomd.conf &
  - cd ..
  - popd
install: cd bloomd && go get -d -v && go build -v
script: go test
